Update variable get to retrieve multiple variables
cyberark/conjur-cli-go pull request #114
Opened 2023-02-24 17:22 UTC by rpothier

### Desired Outcome

*Please describe the desired outcome for this PR.  Said another way, what was
the original request that resulted in these code changes?  Feel free to copy
this information from the connected issue.*

### Implemented Changes

*Describe how the desired outcome above has been achieved with this PR. In
particular, consider:*

- _What's changed? Why were these changes made?_
- _How should the reviewer approach this PR, especially if manual tests are required?_
- _Are there relevant screenshots you can add to the PR description?_

### Connected Issue/Story

Resolves #[relevant GitHub issue(s), e.g. 76]

CyberArk internal issue ID: [insert issue ID]

### Definition of Done
*At least 1 todo must be completed in the sections below for the PR to be
merged.*

#### Changelog

- [ ] The CHANGELOG has been updated, or
- [ ] This PR does not include user-facing changes and doesn't require a
  CHANGELOG update

#### Test coverage

- [ ] This PR includes new unit and integration tests to go with the code
  changes, or
- [ ] The changes in this PR do not require tests

#### Documentation

- [ ] Docs (e.g. `README`s) were updated in this PR
- [ ] A follow-up issue to update official docs has been filed here: [insert issue ID]
- [ ] This PR does not require updating any documentation

#### Behavior

- [ ] This PR changes product behavior and has been reviewed by a PO, or
- [ ] These changes are part of a larger initiative that will be reviewed later, or
- [ ] No behavior was changed with this PR

#### Security

- [ ] Security architect has reviewed the changes in this PR,
- [ ] These changes are part of a larger initiative with a separate security review, or
- [ ] There are no security aspects to these changes

2023-02-27 13:55 UTC, szh commented on go.sum
> +github.com/cyberark/conjur-api-go v0.10.3-0.20230217154521-e01f713716d2/go.mod h1:AbU7bDVW6ygUdgTDCKkh4wyfIVrOtdEeE/r01OE1EYo=
Can you run `go mod tidy`?

2023-02-27 13:55 UTC, szh commented on pkg/cmd/variable.go
> +	variableGetCmd.Flags().StringSliceP("id", "i", ids, "Provide variable identifiers")
Do we need to document how to provide multiple values (ie with a comma separated list)?

2023-02-27 13:55 UTC, szh commented on pkg/cmd/variable.go
> +			cmd.Printf("  %s: %s\n", k, string(v))
This generates json output like this:
```
{
  dev:variable:secret: testing
  dev:variable:top-secret: testing
}
```
Is that the same as the Python CLI used?

2023-02-27 15:33 UTC, rpothier commented on go.sum
> +github.com/cyberark/conjur-api-go v0.10.3-0.20230217154521-e01f713716d2/go.mod h1:AbU7bDVW6ygUdgTDCKkh4wyfIVrOtdEeE/r01OE1EYo=
ran it and will update.

2023-02-27 16:17 UTC, rpothier commented on pkg/cmd/variable.go
> +	variableGetCmd.Flags().StringSliceP("id", "i", ids, "Provide variable identifiers")
good idea, will add.

2023-02-27 17:31 UTC, john-odonnell requested changes

2023-02-28 14:22 UTC, rpothier commented on pkg/cmd/variable.go
> +			cmd.Printf("  %s: %s\n", k, string(v))
The python CLI quotes the variables and only displays the partial id
```
{
    "secret": "123",
    "top-secret": "456"
}
```
Updated to match the Python CLI

2023-03-01 19:51 UTC, john-odonnell requested changes

2023-03-01 19:51 UTC, john-odonnell commented on pkg/cmd/variable.go
> +				data, err = client.RetrieveBatchSecretsSafe(id)
Wonder if there's any detriment to using `RetrieveBatchSecretsSafe` for a single variable instead of using `RetrieveSecret` - did some experimenting with dev environment, and they seem to be equally performant.

2023-03-01 19:51 UTC, john-odonnell commented on pkg/cmd/variable.go
>  			}
This `err` variable is not available outside this block because it was created inside it on line 124. In a case where a `version` is provided but secret retrieval fails, this `err != nil` check won't catch it.

2023-03-01 19:51 UTC, john-odonnell commented on pkg/cmd/variable.go
> +- conjur variable set -i secret -v my_secret_value
nit: `set` example in `get` help.

2023-03-01 19:57 UTC, rpothier commented on pkg/cmd/variable.go
> +- conjur variable set -i secret -v my_secret_value
nice catch, removed that one.

2023-03-01 20:08 UTC, rpothier commented on pkg/cmd/variable.go
>  			}
will fix

2023-03-01 20:09 UTC, rpothier commented on pkg/cmd/variable.go
> +				data, err = client.RetrieveBatchSecretsSafe(id)
They are similar APIs

2023-03-01 21:26 UTC, rpothier commented on pkg/cmd/variable.go
> +				data, err = client.RetrieveBatchSecretsSafe(id)
Here is the REST API for the two versions, there doesn't seem to be much overhead using the batch version.

`curl -H "$(conjur authenticate -H)" http://conjur/secrets/dev/variable/secret`
George
`curl -H "$(conjur authenticate -H)" http://conjur/secrets?variable_ids=dev:variable:secret`
{"dev:variable:secret":"George"}

2023-03-01 21:59 UTC, john-odonnell approved these changes
LGTM 👍

2023-03-01 22:08 UTC, merged