Allow OIDC redirect url to use a configured port
cyberark/conjur-cli-go pull request #117
Opened 2023-03-20 13:31 UTC by szh

### Desired Outcome

In the OIDC login flow, allow the OIDC redirect url to use a custom port (other than 8888). This allows flexibility if the user has another process running on port 8888 or has it blocked for some other reason.

### Implemented Changes

- To determine what port to listen on, the CLI will parse the `redirect_uri` query parameter in the OIDC callback URL returned by Conjur List Authenticators endpoint.
- Unit tests added and reorganized

- After this is released, the CLI docs can be updated. Currently it says "For authentication to the Conjur CLI, the value is always http://127.0.0.1:8888/callback.". This can be changed to indicate that the port can be anything between 1 and 65535, but recommended between 1024 and 65535 based on [RFC 6056 section 3.2](https://www.rfc-editor.org/rfc/rfc6056#section-3.2)

### Connected Issue/Story

CyberArk internal issue ID: CONJSE-1637

#### Changelog

- [x] The CHANGELOG has been updated, or
- [ ] This PR does not include user-facing changes and doesn't require a
  CHANGELOG update

#### Test coverage

- [x] This PR includes new unit and integration tests to go with the code
  changes, or
- [ ] The changes in this PR do not require tests

#### Documentation

- [ ] Docs (e.g. `README`s) were updated in this PR
- [ ] A follow-up issue to update official docs has been filed here: [insert issue ID]
- [ ] This PR does not require updating any documentation

#### Behavior

- [x] This PR changes product behavior and has been reviewed by a PO, or
- [ ] These changes are part of a larger initiative that will be reviewed later, or
- [ ] No behavior was changed with this PR

#### Security

- [x] Security architect has reviewed the changes in this PR,
- [ ] These changes are part of a larger initiative with a separate security review, or
- [ ] There are no security aspects to these changes

2023-03-21 13:29 UTC, doodlesbykumbi requested changes
Some comments before approving

2023-03-21 13:29 UTC, doodlesbykumbi commented on pkg/clients/oidc_callback_server.go
> +func parseAndValidateRedirectPort(redirectURI string) (int, error) {
Since the `redirect URI` can only be `http://127.0.0.1[:port]/callback` we should reduce the input to just a `redirect URI port`. It would simplify the validation too

2023-03-21 13:29 UTC, doodlesbykumbi commented on CHANGELOG.md
> +- OIDC login now supports a custom redirect URL port
1. Have we updated the solution design to reflect this new feature ? 
2. I think we briefly discussed the idea of not allowing the user to specify the port but to instead randomly generate a port, which in Go is achieved by setting the listening port to `:0`. I also think the random port had better security implications. Thoughts ?

2023-03-21 13:32 UTC, szh commented on pkg/clients/oidc_callback_server.go
> +func parseAndValidateRedirectPort(redirectURI string) (int, error) {
Well this function is really doing two things - parsing the port from the redirect uri and then validating it. Perhaps this should be split into two functions.

2023-03-22 12:10 UTC, doodlesbykumbi commented on CHANGELOG.md
> +- OIDC login now supports a custom redirect URL port
1. I saw that in some projects it's been done as a way to document how a solution evolves with time, see https://github.com/cyberark/conjur/tree/master/design/authenticators/authn_jwt. I think it's great approach.
2. I probably need some elaboration here that I'm not sure is best done here. Let's catch up out of band

2023-03-22 12:11 UTC, doodlesbykumbi commented on pkg/clients/oidc_callback_server.go
> +func parseAndValidateRedirectPort(redirectURI string) (int, error) {
I was thinking we shouldn't be ingesting a full URI from the user, and instead should ask for only a port.

2023-03-22 13:11 UTC, szh commented on pkg/clients/oidc_callback_server.go
> +func parseAndValidateRedirectPort(redirectURI string) (int, error) {
We have to get the whole URL from the server - it's the callback url that's stored in the authenticator policy and returned by the 'list authenticators' endpoint.

2023-03-23 23:25 UTC, doodlesbykumbi approved these changes
LGTM! Thanks for addressing the feedback

2023-03-24 13:21 UTC, merged