Remove netgo tag to fix Windows hosts file bug
cyberark/conjur-cli-go pull request #121
Opened 2023-04-03 19:00 UTC by szh

### Desired Outcome

Conjur CLI should use Windows hosts file when present.

### Implemented Changes

`netgo` has a bug that prevents it from using the machine's hosts file on Windows. See https://github.com/golang/go/issues/57757.
This PR disables the `netgo` build flag. It can be reenabled once the above issue is fixed.

### Connected Issue/Story

CyberArk internal issue ID: CNJR-904

#### Changelog

- [x] The CHANGELOG has been updated, or
- [ ] This PR does not include user-facing changes and doesn't require a
  CHANGELOG update

#### Test coverage

- [ ] This PR includes new unit and integration tests to go with the code
  changes, or
- [x] The changes in this PR do not require tests

#### Documentation

- [ ] Docs (e.g. `README`s) were updated in this PR
- [ ] A follow-up issue to update official docs has been filed here: [insert issue ID]
- [x] This PR does not require updating any documentation

#### Behavior

- [ ] This PR changes product behavior and has been reviewed by a PO, or
- [ ] These changes are part of a larger initiative that will be reviewed later, or
- [x] No behavior was changed with this PR

#### Security

- [ ] Security architect has reviewed the changes in this PR,
- [ ] These changes are part of a larger initiative with a separate security review, or
- [x] There are no security aspects to these changes

2023-04-04 13:19 UTC, szh commented
CI is failing due to issue that will be fixed when #120 is merged

2023-04-05 12:20 UTC, doodlesbykumbi requested changes

2023-04-05 12:21 UTC, doodlesbykumbi commented on .goreleaser.yml
> +  # - -tags=netgo
I'm not sure if this template string is the exact thing we want but something to this effect

2023-04-17 14:12 UTC, szh commented on .goreleaser.yml
> +  # - -tags=netgo
Got it working with slightly different syntax - `ne` instead of `not eq`

2023-04-18 14:09 UTC, doodlesbykumbi approved these changes

2023-04-18 14:11 UTC, merged